"""Tests for the DB-backed contact resolver. Uses a synthetic Database.script
fixture (same DDL/INSERT format confirmed live against a real Fakturama 1.6.9
instance) rather than depending on any live install -- portable, fast, no GUI.
"""
from __future__ import annotations

from pathlib import Path

import pytest

from fic.uia.contact_resolver import (
    ContactResolverError,
    normalize_arabic,
    parse_contacts,
    resolve,
    search_key_for,
)

DDL = (
    "CREATE MEMORY TABLE PUBLIC.CONTACTS(ID INTEGER GENERATED BY DEFAULT AS IDENTITY"
    "(START WITH 0) NOT NULL PRIMARY KEY,ACCOUNT VARCHAR(256),ACCOUNT_HOLDER VARCHAR(256),"
    "BANK_CODE VARCHAR(256),BANK_NAME VARCHAR(256),BIC VARCHAR(256),BIRTHDAY VARCHAR(256),"
    "CATEGORY VARCHAR(256),CITY VARCHAR(256),COMPANY VARCHAR(256),COUNTRY VARCHAR(256),"
    "DATE_ADDED VARCHAR(256),DELETED BOOLEAN,DELIVERY_BIRTHDAY VARCHAR(256),"
    "DELIVERY_CITY VARCHAR(256),DELIVERY_COMPANY VARCHAR(256),DELIVERY_COUNTRY VARCHAR(256),"
    "DELIVERY_FIRSTNAME VARCHAR(256),DELIVERY_GENDER INTEGER,DELIVERY_NAME VARCHAR(256),"
    "DELIVERY_STREET VARCHAR(256),DELIVERY_TITLE VARCHAR(256),DELIVERY_ZIP VARCHAR(256),"
    "DISCOUNT DOUBLE,EMAIL VARCHAR(256),FAX VARCHAR(256),FIRSTNAME VARCHAR(256),"
    "GENDER INTEGER,IBAN VARCHAR(256),MANDAT_REF VARCHAR(256),MOBILE VARCHAR(256),"
    "NAME VARCHAR(256),NOTE VARCHAR(32768),NR VARCHAR(256),PAYMENT INTEGER,"
    "PHONE VARCHAR(256),RELIABILITY INTEGER,STREET VARCHAR(256),"
    "SUPPLIERNUMBER VARCHAR(256),TITLE VARCHAR(256),USE_NET_GROSS INTEGER,"
    "VATNR VARCHAR(256),VATNRVALID INTEGER,WEBSITE VARCHAR(256),ZIP VARCHAR(256))\n"
)


def _row(
    id_,
    company="",
    firstname="",
    name="",
    street="",
    zip_="",
    city="",
    country="Germany",
    nr="",
    deleted="FALSE",
    note="",
):
    # positions must match FALLBACK_CONTACTS_COLUMNS / the DDL above exactly
    vals = [
        str(id_), "''", "''", "''", "''", "''", "''", "''",
        f"'{city}'", f"'{company}'", f"'{country}'", "''", deleted,
        "''", "''", "''", "''", "''", "0", "''", "''", "''", "''",
        "0.0E0", "''", "''", f"'{firstname}'", "0", "''", "''", "''",
        f"'{name}'", f"'{note}'", f"'{nr}'", "0", "''", "0",
        f"'{street}'", "''", "''", "-1", "''", "0", "''", f"'{zip_}'",
    ]
    return f"INSERT INTO CONTACTS VALUES({','.join(vals)})\n"


def _write_script(tmp_path: Path, rows: list[str]) -> Path:
    p = tmp_path / "Database.script"
    p.write_text(DDL + "".join(rows), encoding="utf-8")
    return p


# --------------------------------------------------------------------------- #
# Parsing
# --------------------------------------------------------------------------- #


def test_parse_contacts_reads_real_column_layout(tmp_path):
    script = _write_script(
        tmp_path,
        [_row(2, company="Northstar Office GmbH", firstname="Marta", name="Klein",
              street="Friedrichstrasse 88", zip_="10117", city="Berlin", nr="CUST000001")],
    )
    records = parse_contacts(script)
    assert len(records) == 1
    r = records[0]
    assert r.id == 2
    assert r.company == "Northstar Office GmbH"
    assert r.first_name == "Marta"
    assert r.last_name == "Klein"
    assert r.nr == "CUST000001"
    assert r.deleted is False


def test_parse_contacts_handles_embedded_comma_in_note():
    # a NOTE field containing a comma must not desync column alignment
    script_text = DDL + _row(0, company="Acme", note="VIP, handle with care")
    from fic.uia.contact_resolver import _split_sql_values

    inner = script_text.splitlines()[-1]
    inner = inner[inner.index("(") + 1 : inner.rindex(")")]
    fields = _split_sql_values(inner)
    assert fields[9] == "Acme"  # COMPANY position unaffected by the comma in NOTE


def test_parse_contacts_filters_nothing_itself_deleted_rows_included(tmp_path):
    script = _write_script(
        tmp_path,
        [_row(0, company="Gone Co", deleted="TRUE"), _row(1, company="Still Here")],
    )
    records = parse_contacts(script)
    assert len(records) == 2
    assert records[0].deleted is True
    assert records[1].deleted is False


def test_missing_script_file_raises_resolver_error(tmp_path):
    with pytest.raises(ContactResolverError):
        parse_contacts(tmp_path / "does_not_exist.script")


# --------------------------------------------------------------------------- #
# resolve() -- AND-matching, not substring
# --------------------------------------------------------------------------- #


def test_resolve_no_match_returns_empty(tmp_path):
    script = _write_script(tmp_path, [_row(0, company="Other Co", firstname="X", name="Y")])
    result = resolve(company="Acme", first_name="Ahmed", last_name="Ali",
                      zip_code="1", city="Cairo", script_path=script)
    assert result.matches == []


def test_resolve_finds_multiword_name_split_across_columns(tmp_path):
    """The exact bug report: 'Ahmed Ali' fails in the UI's substring search
    because Ahmed/Ali live in separate columns. resolve() compares the real
    columns directly, so this is not an issue here at all."""
    script = _write_script(
        tmp_path,
        [_row(0, company="Acme LLC", firstname="Ahmed", name="Ali",
              zip_="11511", city="Cairo", country="Egypt")],
    )
    result = resolve(company="Acme LLC", first_name="Ahmed", last_name="Ali",
                      zip_code="11511", city="Cairo", script_path=script)
    assert len(result.matches) == 1
    assert result.matches[0].first_name == "Ahmed"


def test_resolve_exact_match_all_five_fields(tmp_path):
    script = _write_script(
        tmp_path,
        [_row(2, company="Northstar Office GmbH", firstname="Marta", name="Klein",
              zip_="10117", city="Berlin", nr="CUST000001")],
    )
    result = resolve(company="Northstar Office GmbH", first_name="Marta", last_name="Klein",
                      zip_code="10117", city="Berlin", script_path=script)
    assert len(result.matches) == 1
    assert result.matches[0].id == 2


def test_resolve_company_mismatch_alone_is_not_a_match(tmp_path):
    """Different company, same everything else: brief's 5-field rule treats
    this as NOT an exact match -- correctly allows re-creation under our own
    rule (the caller then hits Fakturama's own Name+Street check separately,
    which is exactly what the `street` parameter below is for)."""
    script = _write_script(
        tmp_path,
        [_row(2, company="Northstar Office GmbH", firstname="Marta", name="Klein",
              zip_="10117", city="Berlin")],
    )
    result = resolve(company="Different Company", first_name="Marta", last_name="Klein",
                      zip_code="10117", city="Berlin", script_path=script)
    assert result.matches == []


def test_resolve_name_street_collision_surfaces_even_with_different_company(tmp_path):
    """Mirrors Fakturama's own native duplicate-contact rule (Name+Street),
    confirmed live to fire even when our 5-field rule says 'no match'. When
    `street` is supplied, resolve() proactively surfaces this too, instead of
    only discovering it reactively when Fakturama's dialog appears mid-save."""
    script = _write_script(
        tmp_path,
        [_row(2, company="Northstar Office GmbH", firstname="Marta", name="Klein",
              street="Friedrichstrasse 88", zip_="10117", city="Berlin")],
    )
    result = resolve(
        company="Northstar Office GmbH FreshTest", first_name="Marta", last_name="Klein",
        zip_code="10117", city="Berlin", street="Friedrichstrasse 88", script_path=script,
    )
    assert len(result.matches) == 1  # caught via the name+street mirror, not the 5-field rule


def test_resolve_multiple_matches_flagged_ambiguous(tmp_path):
    script = _write_script(
        tmp_path,
        [
            _row(0, company="Acme", firstname="A", name="B", zip_="1", city="X"),
            _row(1, company="Acme", firstname="A", name="B", zip_="1", city="X"),
        ],
    )
    result = resolve(company="Acme", first_name="A", last_name="B",
                      zip_code="1", city="X", script_path=script)
    assert len(result.matches) == 2  # caller routes this to ManualReviewRequired


def test_resolve_ignores_soft_deleted_rows(tmp_path):
    script = _write_script(
        tmp_path,
        [_row(0, company="Acme", firstname="A", name="B", zip_="1", city="X", deleted="TRUE")],
    )
    result = resolve(company="Acme", first_name="A", last_name="B",
                      zip_code="1", city="X", script_path=script)
    assert result.matches == []


def test_duplicate_nr_across_different_real_rows_is_detected(tmp_path):
    """The exact scenario proven live in this project's own test data: two
    genuinely different contacts (different company) sharing one NR after a
    force-restart. Confirms this module surfaces it as a diagnostic rather
    than silently trusting NR as unique."""
    script = _write_script(
        tmp_path,
        [
            _row(2, company="Northstar Office GmbH", firstname="Marta", name="Klein",
                 street="Friedrichstrasse 88", zip_="10117", city="Berlin", nr="CUST000001"),
            _row(3, company="Northstar Office GmbH FreshTest", firstname="Marta", name="Klein",
                 street="Friedrichstrasse 88", zip_="10117", city="Berlin", nr="CUST000001"),
        ],
    )
    result = resolve(company="Something Else Entirely", first_name="Nobody", last_name="Here",
                      zip_code="0", city="Nowhere", script_path=script)
    assert "CUST000001" in result.duplicate_nr_groups
    assert len(result.duplicate_nr_groups["CUST000001"]) == 2


def test_search_key_prefers_last_name_over_nr(tmp_path):
    script = _write_script(
        tmp_path,
        [_row(2, company="Northstar Office GmbH", firstname="Marta", name="Klein",
              zip_="10117", city="Berlin", nr="CUST000001")],
    )
    record = parse_contacts(script)[0]
    assert search_key_for(record) == "Klein"


# --------------------------------------------------------------------------- #
# Arabic normalization
# --------------------------------------------------------------------------- #


def test_normalize_arabic_folds_alef_variants():
    assert normalize_arabic("أحمد") == normalize_arabic("احمد") == normalize_arabic("إحمد")


def test_normalize_arabic_strips_diacritics():
    assert normalize_arabic("مُحَمَّد") == normalize_arabic("محمد")


def test_normalize_arabic_strips_tatweel():
    assert normalize_arabic("احـــمد") == normalize_arabic("احمد")


def test_normalize_arabic_folds_taa_marbuta():
    assert normalize_arabic("فاطمة") == normalize_arabic("فاطمه")


def test_resolve_matches_arabic_name_across_alef_and_diacritic_variants(tmp_path):
    script = _write_script(
        tmp_path,
        [_row(0, company="شركة اكمي", firstname="أحمد", name="علي",
              zip_="11511", city="القاهرة", country="Egypt")],
    )
    result = resolve(
        company="شركة اكمي", first_name="احمد", last_name="عَلِي",  # alef + diacritic variant
        zip_code="11511", city="القاهرة", script_path=script,
    )
    assert len(result.matches) == 1


# --------------------------------------------------------------------------- #
# Tier 1: exact company name takes priority
# --------------------------------------------------------------------------- #


def _northstar_family(tmp_path):
    """The exact live situation that halted a real run: one genuine contact
    plus two test rows sharing the same person AND street, differing only by
    company name. The name+street mirror alone reports all three."""
    return _write_script(
        tmp_path,
        [
            _row(2, company="Northstar Office GmbH", firstname="Marta", name="Klein",
                 street="Friedrichstrasse 88", zip_="10117", city="Berlin", nr="CUST000001"),
            _row(3, company="Northstar Office GmbH FreshTest", firstname="Marta", name="Klein",
                 street="Friedrichstrasse 88", zip_="10117", city="Berlin", nr="CUST000001"),
            _row(4, company="Northstar Office GmbH DupTest2", firstname="Marta", name="Klein",
                 street="Friedrichstrasse 88", zip_="10117", city="Berlin", nr="CUST000002"),
        ],
    )


def test_exact_company_wins_over_name_street_lookalikes(tmp_path):
    script = _northstar_family(tmp_path)
    result = resolve(
        company="Northstar Office GmbH", first_name="Marta", last_name="Klein",
        zip_code="10117", city="Berlin", street="Friedrichstrasse 88",
        script_path=script,
    )
    assert [m.id for m in result.matches] == [2], (
        "exactly one exact company match must be reused outright, not drowned "
        "out by same-person/same-street rows belonging to other companies"
    )


def test_exact_company_match_is_case_and_whitespace_insensitive(tmp_path):
    script = _northstar_family(tmp_path)
    result = resolve(
        company="   nORTHSTAR   office   gmbh   ", first_name="Marta", last_name="Klein",
        zip_code="10117", city="Berlin", street="Friedrichstrasse 88",
        script_path=script,
    )
    assert [m.id for m in result.matches] == [2]


def test_exact_company_match_is_never_partial(tmp_path):
    """'Northstar Office GmbH' must not match '... FreshTest'. Asking for a
    company that exists only as a PREFIX of stored rows falls through to
    tier 2 rather than silently reusing a longer-named company."""
    script = _write_script(
        tmp_path,
        [
            _row(3, company="Northstar Office GmbH FreshTest", firstname="Marta", name="Klein",
                 street="Friedrichstrasse 88", zip_="10117", city="Berlin", nr="CUST000001"),
        ],
    )
    result = resolve(
        company="Northstar Office GmbH", first_name="Marta", last_name="Klein",
        zip_code="10117", city="Berlin", street="Friedrichstrasse 88",
        script_path=script,
    )
    # tier 2's name+street mirror still surfaces it, deliberately -- Fakturama's
    # own duplicate check would fire here, so the caller must still see it.
    assert [m.id for m in result.matches] == [3]


def test_two_identical_company_names_stay_ambiguous(tmp_path):
    script = _write_script(
        tmp_path,
        [
            _row(1, company="Acme GmbH", firstname="A", name="One",
                 street="Road 1", zip_="10117", city="Berlin", nr="C1"),
            _row(2, company="Acme GmbH", firstname="B", name="Two",
                 street="Road 2", zip_="20095", city="Hamburg", nr="C2"),
        ],
    )
    result = resolve(
        company="Acme GmbH", first_name="A", last_name="One",
        zip_code="10117", city="Berlin", street="Road 1", script_path=script,
    )
    assert len(result.matches) == 2, "two live rows sharing a company name must stay ambiguous"


def test_no_company_match_falls_back_to_five_field_rule(tmp_path):
    script = _write_script(
        tmp_path,
        [
            _row(1, company="Totally Different GmbH", firstname="Marta", name="Klein",
                 street="Friedrichstrasse 88", zip_="10117", city="Berlin", nr="C1"),
        ],
    )
    result = resolve(
        company="Nobody Here Ltd", first_name="Marta", last_name="Klein",
        zip_code="10117", city="Berlin", street="Friedrichstrasse 88",
        script_path=script,
    )
    # no exact company -> tier 2; the name+street mirror still catches it
    assert [m.id for m in result.matches] == [1]


def test_deleted_rows_never_win_tier_one(tmp_path):
    script = _write_script(
        tmp_path,
        [
            _row(1, company="Acme GmbH", firstname="A", name="One",
                 street="Road 1", zip_="10117", city="Berlin", nr="C1", deleted="TRUE"),
        ],
    )
    result = resolve(
        company="Acme GmbH", first_name="A", last_name="One",
        zip_code="10117", city="Berlin", script_path=script,
    )
    assert result.matches == []


def test_document_number_exists_detects_used_and_unused(tmp_path):
    from fic.uia.contact_resolver import document_number_exists

    script = tmp_path / "Database.script"
    script.write_text(
        DDL + "INSERT INTO DOCUMENTS VALUES(1,'','',5,3,'','REF','2026-01-01',"
        "FALSE,'',0.0E0,0,0,1,FALSE,'2',0.0E0,'','','','PO000007',1)\n",
        encoding="utf-8",
    )
    assert document_number_exists("PO000007", script) is True
    assert document_number_exists("PO000008", script) is False
    assert document_number_exists("", script) is False


def test_document_number_exists_also_searches_the_write_ahead_log(tmp_path):
    """Saves made since the last checkpoint live in Database.log, and those are
    exactly the ones a desynced counter collides with."""
    from fic.uia.contact_resolver import document_number_exists

    script = tmp_path / "Database.script"
    script.write_text(DDL, encoding="utf-8")
    (tmp_path / "Database.log").write_text(
        "INSERT INTO DOCUMENTS VALUES(2,'','',5,3,'','R','2026-01-01',FALSE,'',"
        "0.0E0,0,0,2,FALSE,'3',0.0E0,'','','','PO000099',1)\n",
        encoding="utf-8",
    )
    assert document_number_exists("PO000099", script) is True


def test_parse_contacts_also_reads_the_write_ahead_log(tmp_path):
    """A contact created since the last checkpoint lives only in Database.log.
    Live failure this covers: the resolver kept reporting an older contact as
    the sole match because the one just created was invisible to it."""
    script = _write_script(
        tmp_path,
        [_row(1, company="Old GmbH", firstname="A", name="One",
              street="Road 1", zip_="10117", city="Berlin", nr="C1")],
    )
    (tmp_path / "Database.log").write_text(
        _row(2, company="Fresh GmbH", firstname="B", name="Two",
             street="Road 2", zip_="20095", city="Hamburg", nr="C2"),
        encoding="utf-8",
    )
    ids = {c.id for c in parse_contacts(script)}
    assert ids == {1, 2}

    result = resolve(
        company="Fresh GmbH", first_name="B", last_name="Two",
        zip_code="20095", city="Hamburg", script_path=script,
    )
    assert [m.id for m in result.matches] == [2]


# --------------------------------------------------------------------------- #
# Idempotency: has this order already been saved?
# --------------------------------------------------------------------------- #

DOCS_DDL = (
    "CREATE MEMORY TABLE PUBLIC.DOCUMENTS(ID INTEGER NOT NULL PRIMARY KEY,"
    "ADDRESS VARCHAR(256),ADDRESSFIRSTLINE VARCHAR(256),ADDRESSID INTEGER,"
    "CATEGORY INTEGER,CONSULTANT VARCHAR(256),CUSTOMERREF VARCHAR(256),"
    "DATE VARCHAR(256),DELETED BOOLEAN,NAME VARCHAR(256))\n"
)


def _doc(id_, ref, name, deleted="FALSE"):
    return (
        f"INSERT INTO DOCUMENTS VALUES({id_},'addr','first',5,3,'',"
        f"'{ref}','2026-01-01',{deleted},'{name}')\n"
    )


def _write_docs(tmp_path, rows, log_rows=()):
    p = tmp_path / "Database.script"
    p.write_text(DOCS_DDL + "".join(rows), encoding="utf-8")
    if log_rows:
        (tmp_path / "Database.log").write_text("".join(log_rows), encoding="utf-8")
    return p


def test_finds_an_already_saved_order_by_reference(tmp_path):
    from fic.uia.contact_resolver import find_orders_by_reference

    script = _write_docs(tmp_path, [_doc(1, "WEB-2026-0714-A17", "PO000009")])
    hits = find_orders_by_reference("WEB-2026-0714-A17", script)
    assert [h["document"] for h in hits] == ["PO000009"]
    assert find_orders_by_reference("WEB-2026-0714-A18", script) == []
    assert find_orders_by_reference("", script) == []


def test_idempotency_matches_the_column_not_the_whole_line(tmp_path):
    """A substring search over the file would match this reference appearing in
    an address and refuse to run for entirely the wrong reason."""
    from fic.uia.contact_resolver import find_orders_by_reference

    script = tmp_path / "Database.script"
    script.write_text(
        DOCS_DDL
        + "INSERT INTO DOCUMENTS VALUES(1,'REF-123 Street','first',5,3,'',"
        "'SOMETHING-ELSE','2026-01-01',FALSE,'PO000001')\n",
        encoding="utf-8",
    )
    assert find_orders_by_reference("REF-123", script) == []


def test_idempotency_ignores_deleted_documents(tmp_path):
    from fic.uia.contact_resolver import find_orders_by_reference

    script = _write_docs(tmp_path, [_doc(1, "REF-9", "PO000001", deleted="TRUE")])
    assert find_orders_by_reference("REF-9", script) == []


def test_idempotency_also_sees_the_write_ahead_log(tmp_path):
    """The order saved by the PREVIOUS run is usually still only in the log."""
    from fic.uia.contact_resolver import find_orders_by_reference

    script = _write_docs(tmp_path, [], log_rows=[_doc(2, "REF-LOG", "PO000042")])
    assert [h["document"] for h in find_orders_by_reference("REF-LOG", script)] == ["PO000042"]
